services:
  - type: web
    name: obshta-kultura-quiz
    env: dotnet
    buildCommand: dotnet publish -c Release
    startCommand: dotnet Obshta_Kultura.dll
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://+:10000 