services:
  - type: web
    name: obshta-kultura-quiz
    env: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://+:10000
    healthCheckPath: /
    autoDeploy: true 