services:
  - type: web
    name: obshta-kultura-quiz
    env: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://+:80
      - key: PORT
        value: 80
    healthCheckPath: /
    autoDeploy: true
    disk:
      name: data
      mountPath: /app/data
      sizeGB: 1 